[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pylibre"
version = "0.1.0"
description = "Interface de linha de comando para converter EPUB em texto puro"
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
pylibre = "pylibre.cli:main"

[tool.setuptools]
packages = ["pylibre"]
